# Generated by Django 4.2.11 on 2024-12-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Website',
            new_name='Tabella_immagini',
        ),
    ]
