# Generated by Django 4.2.11 on 2024-12-22 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_rename_tabella_immagini_website'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Website',
            new_name='Tabella_immagini',
        ),
    ]
